# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

ARDUINO_DIR = /usr/share/arduino
ARDMK_DIR = /usr/share/arduino
AVR_TOOLS_DIR = /usr

AVRDUDE = /usr/bin/avrdude
AVRDUDE_CONF = /etc/avrdude.conf

ARDUINO_VERSION = 1.6.11
BOARD_TAG = pro
BOARD_SUB = 16MHzatmega328
ARDUINO_PORT = /dev/ttyUSB0

include /usr/share/arduino/Arduino.mk
